spring:
  profiles:
    include: native,default
  cloud:
    config:
      discovery:
        enabled: false
      server:
        native:
          searchLocations: C:/Users/config
        encrypt:
          enabled: true
server:
  port: 8888